### ISSUE TITLE
TCP作为服务器时候，不能给客户端发送数据

### ISSUE THREAD

**Issue by woddle** [sige5193/bittly#18]
测试用bittly创建一个TCP服务器，当有客户端连接时候：
客户端发送数据可以接收到，但是服务器发送给客户端，客户端接收不到数据

**Comment by sige5193** [comment]
我刚刚试了一下收发可以用， 应该是有什么错误没有显示出来， 可以试试 "文件" > "打开开发者工具" 看下有啥错误没有 ~~~
