### ISSUE TITLE
在脚本中增加时间戳转换函数，支持自定义日期格式转换

### ISSUE THREAD

**Issue by lvbiaocheng** [sige5193/bittly#31]
![时间戳转换函数](https://user-images.githubusercontent.com/124508314/216823541-8477acff-8508-499b-a9a5-1a878ff76176.png)

**Comment by sige5193** [comment]
已增加到快捷调用和脚本中
![2023020610222401](https://user-images.githubusercontent.com/4973533/216868822-bce495fe-d188-4c6f-a55a-a814a945a4b1.png)
![2023020610231601](https://user-images.githubusercontent.com/4973533/216868842-e98a5fb2-d46c-40ec-8c3c-5be5406bbc67.png)

标记参考：https://www.php.net/manual/zh/datetime.format.php
