### ISSUE TITLE
ubuntu 22.04LTS 无法获取串口

### ISSUE THREAD

**Issue by maplerian** [sige5193/bittly#38]
串口信息：
crw-rw----+ 1 root plugdev 166, 0  2月 18 09:49 /dev/ttyACM0
当前用户已经添加 串口组 权限

软件现象：
无法搜索到串口， 显示空白

**Comment by maplerian** [comment]
页面端可以获取到串口：https://bittly.sigechen.com/app
就是独立的桌面程序无法获取

**Comment by sige5193** [comment]
已修复
