### ISSUE TITLE
工具-终端-SerialPort选项，无法打开串口

### ISSUE THREAD

**Issue by cgy233** [sige5193/bittly#68]
## 
想使用串口自动回复功能，在工具栏选择工具-终端-SerialPort，选择确认未被占用的串口进行启动，提示错误：
```bash
TypeError: Cannot read properties of undefined (reading 'getters)
```
![serialport_err](https://user-images.githubusercontent.com/57333094/236594522-3c35208c-ff1f-4207-a2ab-fdcf7c62a5c8.png)

**Comment by sige5193** [comment]
自动回复被挪到主面板的MOCK模块那里去了， 这个终端吧 ~~~ 还在想要不要删掉 ~~~

**Comment by cgy233** [comment]
> 自动回复被挪到主面板的MOCK模块那里去了， 这个终端吧 ~~~ 还在想要不要删掉 ~~~

啊这...我搜看文档找到那里的，mock模块看不懂是自动回复功能耶，直接标自动化可能还是比较直白点

**Comment by sige5193** [comment]
我还是在提示加点描述吧， 叫MOCK主要是因为不知道怎么翻译过来合适， 毕竟自动回复只是其中一个功能， 主要是想实现服务端或者设备的模拟 ~~~
