### ISSUE TITLE
输出的PDF文档乱码

### ISSUE THREAD

**Issue by YangAoTeng** [sige5193/bittly#77]
![Snipaste_2024-03-04_11-14-16](https://github.com/sige5193/bittly/assets/35907267/11d3fe2c-5b86-4dc8-b517-336dee574f84)

**Comment by YangAoTeng** [comment]
请问使用什么字体输出才不会乱码

**Comment by sige5193** [comment]
需要单独加载字体才行， windows上自带的字体 ttf 等应该就可以， 因为之前自带的字体文件太大了，所以移除了 ~~~

**Comment by YangAoTeng** [comment]
我使用微软楷体、雅黑等，协议的字体全是乱码的，其余位置正常
[默认项目.pdf](https://github.com/sige5193/bittly/files/14476161/default.pdf)

**Comment by sige5193** [comment]
额 ~~~ 貌似需要先转换一下才能用 ~~~
https://github.com/parallax/jsPDF?tab=readme-ov-file#use-of-unicode-characters--utf-8

**Comment by YangAoTeng** [comment]
en。。。 转换好像生成的是js文件，我好像要去自己编译了
