### ISSUE TITLE
npm ERR! command git --no-replace-objects ls-remote https://git.sigechen.com/sige/node-modbus-serial.git

### ISSUE THREAD

**Issue by lyongdee** [sige5193/bittly#78]
npm install的时候报这个错误了：

![image](https://github.com/sige5193/bittly/assets/369124/2173c7eb-86be-474f-bd01-0e628f4a1e72)

**Comment by sige5193** [comment]
node-modbus-serial 库的地址替换成 github 的地址即可 ~~~
